version: '3.3'

services:
  postgres:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4poIpTyd
      POSTGRES_DB: haulin-be